config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home', to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'keys#index'
  resources :keys
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/key.rb
class Key < ApplicationRecord
  belongs_to :user

  include PgSearch::Model
  pg_search_scope :search_full_text,
    against: {
      name: 'A',
      account: 'B',
      url: 'C'
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :keys
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/keys_controller.rb
class KeysController < ApplicationController
  before_action :set_key, only: [:destroy, :edit, :update]

  def index
    @key = Key.new
    if params[:query].present?
      @keys = Key.search_full_text(params[:query])
    else
      @keys = Key.all
    end
    # @keys = Key.all
  end

  def new
    @key = Key.new
  end

  def create
    @key = Key.new(key_params)
    @key.user = current_user
    # @plant.user = current_user

    if @key.save
      redirect_to root_path
    # else
    #   render root_path
    end
  end

  def edit
  end

  def destroy
    @key = Key.find(params[:id])
    @key.destroy
    redirect_to root_path
  end

  def update
    if @key.update(key_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def set_key
    @key = Key.find(params[:id])
  end

  def key_params
    params.require(:key).permit(:name, :account, :password, :url, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/keys/edit.html.erb
<div class="container">
  <div class="d-flex align-items-center flex-column">
    <div class="link-box mt-3">
      <h5 class="m-0"><%= link_to '< back', root_path %></h5>
    </div>
    <div class="passwordly-card passwordly-corners mt-3 p-4">
      <%= simple_form_for @key do |f| %>
        <%= f.input :name, input_html: { class: 'key-input' } %>
        <%= f.input :account, input_html: { class: 'key-input' } %>
        <%= f.input :password, input_html: { class: 'key-input' } %>
        <%= f.input :url, input_html: { class: 'key-input' } %>
        <div class="text-center">
          <%= f.submit 'Update', class: "passordly-button info text-white" %>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/keys/index.html.erb
<div class="add-key d-sm-none d-md-flex align-items-center">
  <p class="m-0 mr-3">Add Passkey</p>
  <button type="button" class="add-key-button" data-toggle="modal" data-target="#exampleModal">
    <i class="fas fa-plus"></i>
  </button>
</div>
<!-- Button trigger modal -->

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content border-0 passwordly-corners">
      <div class="modal-header border-0">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body p-4">
        <%= simple_form_for @key, html: { autocomplete: 'off' } do |f| %>
          <%= f.input :name, input_html: { class: 'key-input' } %>
          <%= f.input :account, input_html: { class: 'key-input' } %>
          <%= f.input :password, input_html: { class: 'key-input' } %>
          <%= f.input :url, input_html: { class: 'key-input' } %>
          <div class="text-center">
            <%= f.submit 'Create', class: "passordly-button info text-white" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container d-flex flex-column align-items-center text-center mt-4 mb-4">
  <!-- Search Bar -->
  <div class="row justify-content-center">
    <%= form_tag keys_path, method: :get, class: "form-inline my-2 my-lg-0" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "key-search-bar",
        placeholder: "Find key..."%>
      <%#= render 'shared/round_button' %>
      <div class="key-button-holder">
        <!-- Button's underlying image asset -->
        <div class="brand-button-circle d-flex justify-content-center align-items-center text-white">
          <i class="fas fa-search"></i>
        </div>
        <!-- Overlying link -->
        <%= submit_tag "", class: "brand-button" %>
      </div>
      <%#= submit_tag "", class: "brand-button" %>
    <% end %>
  </div>
  <!-- Keys -->
  <% if @keys.count == 0 %>
  <div class="mt-4">
    <p>No keys found... </p>
  </div>
  <% end %>
  <% @keys.each do |key| %>
    <% if key.user == current_user %>
      <div class="card passwordly-card passwordly-corners border-0 mt-3">
        <div class="card-body">

          <div class="text-left">
            <div class="card-title">
              <h5><%= key.name %></h5>
            </div>
            <p><i class="fas fa-user-circle"></i> <%= key.account %></p>
            <% pass = "•" * key.password.length %>
            <div class="card password-text border-0">
              <p class="password-text"><i class="fas fa-key"></i> <%= pass %></p>
              <!-- <p type="password"><%= key.password %></p> -->
              <% key_copy_function = "myFunction("+"\"#{key.password}\""+")" %>
              <% key_copy_function %>
              <a class="stretched-link" onclick="<%= key_copy_function %>"></a>
            </div>
            <div class="link-text card border-0">
              <a href="https://<%= key.url %>" target="_blank"><i class="fas fa-link"></i> www.<%= key.name.downcase.gsub(/\s+/, "") %>.com</a>
            </div>
          </div>
          <div class="d-flex justify-content-end key-card-links">
            <h5 class="edit-link"><%= link_to "Edit", edit_key_path(key) %></h5>
            <h5 class="delete-link ml-2"><%= link_to "Delete", key_path(key), method: :delete %></h5>
          </div>

        </div>
      </div>
    <% else %>
    <% end %>
  <% end %>
</div>

<script>
function myFunction(key) {
  console.log(key);
  // Create new element
   var el = document.createElement('textarea');
   // Set value (string to be copied)
   el.value = key;
   // Set non-editable to avoid focus and move outside of view
   el.setAttribute('readonly', '');
   el.style = {position: 'absolute', left: '-9999px'};
   document.body.appendChild(el);
   // Select text inside element
   el.select();
   // Copy text to clipboard
   document.execCommand('copy');
   // Remove temporary element
   document.body.removeChild(el);
  alert("Password copied to clipboard!");
}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Passwordly</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag asset_path('passwordly-favicon.svg') %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-screen">
  <p>A simple home for your keys</p>
  <div class="d-flex flex-column flex-sm-column flex-lg-row">
    <button class="passordly-button info"><%= link_to "Login", new_user_session_path, class: "text-white" %></button>
    <button class="passordly-button primary"><%= link_to "Sign up", new_user_registration_path, class: "text-white" %></button>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%#= image_tag asset_path("passwordly-logo.png"), alt: "alttext" %>
    <% image_tag("passwordly-logo.png", alt: "Passwordly") %>
    <%#= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <!-- Button trigger modal -->
        <button type="button" class="btn" data-toggle="modal" data-target="#exampleModalCenter">
          <%= image_tag asset_path("logout-icon.svg"), class: "logout-icon dropdown-toggle" %>
        </button>
      <% else %>
      <% end %>
    </ul>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-sm modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header border-0">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center mb-4">
        <button class="logout-button"><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "text-white" %></button>
        <%#= link_to "Log out", destroy_user_session_path, method: :delete, class: "logout-button warning" %>
      </div>
    </div>
  </div>
</div>